
import { StyleOption, GalleryItem, Language } from './types';

export const STYLES: StyleOption[] = [
  {
    id: 1,
    prompt: "Flat Vector Art illustration. Adobe Illustrator style, clean bold lines, solid colors, cel-shaded, digital art, sharp edges, minimalist shading, vibrant commercial art style",
    previewColor: "bg-blue-500"
  },
  {
    id: 2,
    prompt: "Hand-drawn Marker Illustration. Alcohol marker texture, rough ink outlines, loose artistic strokes, sketchbook aesthetic, bleeding ink effects, organic and expressive",
    previewColor: "bg-orange-500"
  },
  {
    id: 4,
    prompt: "Risograph Print. Visible halftone dot patterns, misaligned color layers (CMYK offset), grain texture, limited retro color palette, rough paper texture",
    previewColor: "bg-pink-500"
  },
  {
    id: 5,
    prompt: "3D Character Render. Disney/Pixar style, soft ambient occlusion, matte plastic toy texture, smooth surfaces, cute proportions, rim lighting, 3d modeling",
    previewColor: "bg-red-500"
  },
  {
    id: 8,
    prompt: "American Comic Book Art. Bold black ink contours, Ben-Day dots shading, dramatic high-contrast lighting, dynamic superhero art style, vibrant primary colors",
    previewColor: "bg-indigo-600"
  },
  {
    id: 10,
    prompt: "1930s Rubber Hose Animation. Vintage retro cartoon, monochrome black and white, simple rounded shapes, pie-cut eyes, bouncy curved limbs, old film grain",
    previewColor: "bg-gray-800"
  },
  {
    id: 11,
    prompt: "Noir Graphic Novel. High contrast black and white ink, dramatic Chiaroscuro lighting, heavy shadows, mysterious atmosphere, Frank Miller style art",
    previewColor: "bg-neutral-900"
  },
  {
    id: 13,
    prompt: "Cinematic Seinen Graphic Novel illustration. Realistic human anatomy and facial proportions, intricate black ink pen linework with delicate cross-hatching and contour shading, moody chiaroscuro lighting with dramatic deep shadows, warm amber lamp rim-lighting, painterly realistic skin tones with subtle sweat sheen and flushed undertones, mature emotional narrative comic art, clean die-cut white sticker border, transparent background, crisp vector cutout sticker",
    previewColor: "bg-amber-900"
  },
  {
    id: 14,
    prompt: "Modern Korean manhwa webtoon style, semi-realistic digital comic art, delicate sharp ink linework with clean tapering, handsome realistic facial features and expressive eyes, defined anatomy structure, warm skin rendering with subtle flushed blush, atmospheric cinematic rim light, stylized atmospheric smoke vapor with clean outlines if contextually fitting, professional die-cut sticker with thick solid white border outline, isolated on pure solid white background",
    previewColor: "bg-rose-950"
  },
  {
    id: 15,
    prompt: "Harmonious blend of Modern Korean Manhwa (#14, 55%), Sharp Flat Vector Art (#01, 30%), and Seinen Fine Hatching (#13, 10%), with 3% subtle 3D character ambient occlusion volume (#05) and 2% vintage cartoon ink bounce (#10). Refined manhwa facial proportions and expressive eyes, bold clean vector contour lines, crisp cel-shaded color blocks balanced with delicate localized ink hatching, smooth 2.5D skin depth with subtle warm blush, clean die-cut sticker with thick white border outline, isolated on pure solid white background",
    previewColor: "bg-teal-700"
  },
  {
    id: 16,
    prompt: "Sophisticated fusion of Cinematic Seinen Graphic Novel (#13, 50%), 1930s Vintage Retro Ink Aesthetic (#10, 30%), and Korean Manhwa facial refinement (#14, 15%), enriched with 3% soft 3D dimensional lighting (#05) and 2% crisp vector precision. Realistic anatomical structure with moody chiaroscuro deep shadow contrasts, fine cross-hatching combined with rich vintage black ink washes, subtle warm monochromatic tone with delicate flushed highlight accents, collectible die-cut sticker with thick white border, isolated on pure solid white background",
    previewColor: "bg-stone-800"
  },
  {
    id: 17,
    prompt: "Cutting-edge fusion of High-contrast Cel-Shaded Vector (#01, 45%), Korean Webtoon Manhwa Glamour (#14, 35%), and Dynamic Rubber Hose fluid curved line rhythm (#10, 15%), with 5% premium 3D designer vinyl toy ambient occlusion depth (#05). Sharp tapered black ink contours, vivid color saturation with pristine flat and soft-gradient transitions, handsome webtoon facial details with cinematic rim lighting, polished collectible vinyl sticker look, die-cut sticker with thick white border outline, isolated on pure solid white background",
    previewColor: "bg-cyan-800"
  }
];

export const TRANSLATIONS = {
  'zh-TW': {
    header_title: "Sticker Maker Pro",
    header_subtitle: "AI 貼圖製作工具",
    nav_create: "製作貼圖",
    nav_gallery: "探索藝廊",
    nav_history: "我的貼圖集",
    welcome_title: "歡迎使用 Sticker Maker Pro!",
    welcome_desc: "請上傳一張肖像照片開始製作！如果您沒有指定風格，我會預設使用",
    welcome_default_style: "[1] 向量賽璐珞風格",
    step1_title: "1. 選擇風格",
    step1_selected: "目前選擇",
    step2_title: "2. 上傳肖像照片",
    step2_drag: "點擊或拖放照片至此",
    step2_hint: "支援 JPG, PNG (建議使用清晰的半身肖像)",
    step2_ready: "照片準備就緒！",
    step2_reedit: "重新編輯",
    step2_change: "更換照片",
    editor_title: "調整您的照片",
    editor_desc: "請縮放、移動或旋轉，確保主體位於中央以獲得最佳效果。",
    editor_btn_confirm: "確認使用",
    editor_btn_cancel: "取消",
    editor_rotate: "旋轉",
    editor_zoom: "縮放",
    processing_title: "製作中",
    processing_steps: [
      "正在初始化 Sticker Maker Pro...",
      "步驟 2/4: 智慧去背與主體分離中...",
      "步驟 3/4: 應用風格與向量化轉換...",
      "步驟 4/4: 最終驗證與裁切...",
    ],
    processing_set: "正在製作擴展套裝貼圖 (一組 3 張)...",
    result_verified: "驗證通過：512x512px PNG",
    result_title: "您的貼圖已完成！",
    result_style_label: "風格",
    result_saved: "已儲存至您的貼圖集",
    btn_magic_wand: "一鍵去背修復",
    btn_reset: "製作下一張",
    btn_reuse: "用同張圖換風格",
    btn_generate_set: "製作擴展套裝",
    btn_download: "下載 PNG",
    btn_retry: "再試一次 (Retry)",
    set_title: "擴展套裝貼圖已完成！",
    set_desc: "基於您的原圖，我們生成了風格統一但表情動作不同的貼圖。",
    error_header: "哎呀！製作過程出了點問題",
    error_upload: "讀取檔案時發生錯誤",
    error_process: "製作失敗，請稍後再試或更換照片。",
    error_safety: "內容觸發了安全過濾機制，請更換圖片再試。",
    error_timeout: "伺服器反應時間過長，可能是目前負載較大。",
    error_no_image: "AI 未能生成有效的貼圖圖片。",
    error_cancelled: "已取消這次生成。",
    validation_file_type: "僅支援 PNG、JPEG、WebP 格式的圖片。",
    validation_file_size: "圖片檔案大小超過 10 MB 上限，請換一張試試。",
    validation_file_corrupt: "無法讀取這張圖片，檔案可能已損壞。",
    cancel: "取消",
    footer: "© 2024 Sticker Maker Pro. Powered by Google Gemini.",
    gallery_title: "精選範例 (Sample Gallery)",
    gallery_subtitle: "看看大家使用這些風格製作出的精彩貼圖，或是選擇一個範例來試試看！",
    gallery_btn_try: "套用此風格",
    gallery_btn_import: "匯入範例圖",
    history_title: "我的貼圖集",
    history_subtitle: "您在本機製作的所有貼圖",
    history_empty: "尚未製作任何貼圖。快去製作第一張吧！",
    variation_title: "基於上一張圖片生成變體",
    variation_subtitle: "保持相同的藝術風格與人物主體，依照設定的變體強度生成生動的新表情與動作！",
    variation_strength_label: "變體強度 (Variation Intensity)",
    variation_strength_low: "微幅微調 (Subtle)",
    variation_strength_low_desc: "微調表情（如眨眼、微笑、微傾），主體姿勢高度一致",
    variation_strength_medium: "標準變體 (Moderate)",
    variation_strength_medium_desc: "顯著表情與手勢（如比讚、歡笑、手托下巴），風格特徵統一",
    variation_strength_high: "大幅創意 (Creative)",
    variation_strength_high_desc: "豐富動態動作與趣味情緒（戴墨鏡、歡呼跳躍、生動特效）",
    variation_prompt_label: "變體動作/表情（可選情境標籤或自行輸入）",
    variation_prompt_placeholder: "例如：開懷大笑、戴帥氣墨鏡、雙手比心、吃驚大呼...",
    btn_generate_variation: "⚡ 生成強度變體貼圖",
    btn_create_variation_short: "製作變體",
    variation_compare_title: "原貼圖與新變體對比",
    compare_original: "上一張原圖",
    compare_variation: "新生成變體",
    tag_variation: "變體貼圖",
    processing_variation: "正在分析上一張貼圖的主體特徵與風格，生成同款變體貼圖...",
    styles: {
      1: { name: "向量賽璐珞風", features: "粗黑輪廓、平滑漸層" },
      2: { name: "手繪麥克筆風", features: "手繪線條、筆觸感" },
      4: { name: "孔版印刷風", features: "網點、錯位疊印" },
      5: { name: "美式卡通風", features: "粗線條、微立體感" },
      8: { name: "圖像小說風", features: "漫畫風格、高對比陰影" },
      10: { name: "復古橡膠管卡通", features: "30年代動畫、黑白線條" },
      11: { name: "黑白電影偵探風", features: "純黑白、強烈光影" },
      13: { name: "青年寫實漫畫風", features: "寫實人體比例、細膩排線、電影感光影與汗水光澤" },
      14: { name: "韓漫精緻寫實風", features: "細緻墨線、美型寫實、微醺光影、淡麗膚色" },
      15: { name: "潮流美型向量漫", features: "55%韓漫美型 + 30%俐落向量 + 10%寫實排線 + 5%微立體調味" },
      16: { name: "復古墨繪青年誌", features: "50%青年暗調 + 30%老動畫墨韻 + 15%美型神態 + 5%微立體光澤" },
      17: { name: "新潮賽璐珞美型漫", features: "45%純色賽璐珞 + 35%韓漫光彩 + 15%流暢曲度 + 5%公仔立體感" },
    }
  },
  'en': {
    header_title: "Sticker Maker Pro",
    header_subtitle: "AI Sticker Generator",
    nav_create: "Create",
    nav_gallery: "Gallery",
    nav_history: "Collection",
    welcome_title: "Welcome to Sticker Maker Pro!",
    welcome_desc: "Upload a portrait photo to start! If no style is specified, I will default to",
    welcome_default_style: "[1] Modern Vector Style",
    step1_title: "1. Choose Style",
    step1_selected: "Selected",
    step2_title: "2. Upload Photo",
    step2_drag: "Click or drag photo here",
    step2_hint: "Supports JPG, PNG (Clear portrait recommended)",
    step2_ready: "Photo Ready!",
    step2_reedit: "Edit",
    step2_change: "Change Photo",
    editor_title: "Adjust Your Photo",
    editor_desc: "Zoom, pan, and rotate to frame the subject perfectly.",
    editor_btn_confirm: "Confirm",
    editor_btn_cancel: "Cancel",
    editor_rotate: "Rotate",
    editor_zoom: "Zoom",
    processing_title: "Processing",
    processing_steps: [
      "Initializing Sticker Maker Pro...",
      "Step 2/4: Removing background...",
      "Step 3/4: Applying style & vectorizing...",
      "Step 4/4: Final validation & cropping...",
    ],
    processing_set: "Generating expanded sticker set (3 variations)...",
    result_verified: "Verified: 512x512px PNG",
    result_title: "Sticker Ready!",
    result_style_label: "Style",
    result_saved: "Saved to Collection",
    btn_magic_wand: "Fix Background",
    btn_reset: "Start New",
    btn_reuse: "Reuse Photo",
    btn_generate_set: "Generate Set",
    btn_download: "Download PNG",
    btn_retry: "Retry Generation",
    set_title: "Sticker Set Ready!",
    set_desc: "Based on your original, we've created a series with consistent style but different expressions.",
    error_header: "Oops! Something went wrong",
    error_upload: "Error reading file",
    error_process: "Processing failed, please try again or use a different photo.",
    error_safety: "Content was blocked by safety filters. Please try another image.",
    error_timeout: "Server took too long to respond. High load detected.",
    error_no_image: "AI failed to produce a valid image result.",
    error_cancelled: "Generation was cancelled.",
    validation_file_type: "Only PNG, JPEG, and WebP images are supported.",
    validation_file_size: "Image is larger than the 10 MB limit. Please try a smaller file.",
    validation_file_corrupt: "Could not read this image. The file may be corrupt.",
    cancel: "Cancel",
    footer: "© 2024 Sticker Maker Pro. Powered by Google Gemini.",
    gallery_title: "Sample Gallery",
    gallery_subtitle: "See what others are creating or import a sample to start testing!",
    gallery_btn_try: "Use Style",
    gallery_btn_import: "Import Sample",
    history_title: "My Collection",
    history_subtitle: "All stickers you created on this device",
    history_empty: "No stickers yet. Go create your first one!",
    variation_title: "Generate Variation from Sticker",
    variation_subtitle: "Preserve the exact character and art style while varying expression and pose by intensity!",
    variation_strength_label: "Variation Intensity",
    variation_strength_low: "Subtle (Low)",
    variation_strength_low_desc: "Minor expression shift (smile, wink), nearly identical posture",
    variation_strength_medium: "Moderate (Medium)",
    variation_strength_medium_desc: "Noticeable expression & gesture (thumbs up, laughing, waving)",
    variation_strength_high: "Creative (High)",
    variation_strength_high_desc: "Dynamic action, vivid reactions, playful sticker accessories",
    variation_prompt_label: "Action / Theme Prompt (Optional quick tags or custom text)",
    variation_prompt_placeholder: "e.g. laughing heartily, stylish sunglasses, heart hands...",
    btn_generate_variation: "⚡ Generate Variation",
    btn_create_variation_short: "Make Variation",
    variation_compare_title: "Compare Original & Variation",
    compare_original: "Previous Sticker",
    compare_variation: "New Variation",
    tag_variation: "Variation",
    processing_variation: "Analyzing previous sticker character and style to generate variation...",
    styles: {
      1: { name: "Modern Vector", features: "Thick outlines, smooth gradients" },
      2: { name: "Analog Marker", features: "Expressive ink lines, marker texture" },
      4: { name: "Risograph", features: "Halftone dots, color misalignment" },
      5: { name: "American Cartoon", features: "Bold 2.5D, fluid outlines" },
      8: { name: "Graphic Novel", features: "Heavy shadows, high contrast" },
      10: { name: "Rubber Hose", features: "1930s animation, monochrome" },
      11: { name: "Film Noir", features: "Black & white, dramatic lighting" },
      13: { name: "Cinematic Graphic Novel", features: "Realistic anatomy, cross-hatching, moody lighting & sweat sheen" },
      14: { name: "Korean Manhwa Style", features: "Delicate ink lines, handsome semi-realism, moody rim light, warm skin tone" },
      15: { name: "Manhwa Pop Vector", features: "55% Manhwa + 30% Vector + 10% Seinen Hatching + 5% 3D touch" },
      16: { name: "Vintage Noir Graphic", features: "50% Seinen Noir + 30% 1930s Ink + 15% Manhwa + 5% Soft 3D" },
      17: { name: "Neo-Cel Manhwa 3D", features: "45% Cel-Vector + 35% Manhwa + 15% Fluid Rhythm + 5% Vinyl Toy 3D" },
    }
  },
  'ja': {
    header_title: "Sticker Maker Pro",
    header_subtitle: "AIステッカー作成ツール",
    nav_create: "作成",
    nav_gallery: "ギャラリー",
    nav_history: "コレクション",
    welcome_title: "Sticker Maker Proへようこそ!",
    welcome_desc: "写真をアップロードして始めましょう！スタイルが指定されていない場合、デフォルトで",
    welcome_default_style: "[1] ベクターセルロイド風",
    step1_title: "1. スタイルを選択",
    step1_selected: "選択中",
    step2_title: "2. 写真をアップロード",
    step2_drag: "クリックまたは写真をドラッグ",
    step2_hint: "JPG, PNG対応 (鮮明なポートレート推奨)",
    step2_ready: "写真の準備完了！",
    step2_reedit: "編集する",
    step2_change: "写真を変更",
    editor_title: "写真を調整",
    editor_desc: "拡大・縮小、移動、回転を行い、被写体を中央に配置してください。",
    editor_btn_confirm: "完了",
    editor_btn_cancel: "キャンセル",
    editor_rotate: "回転",
    editor_zoom: "ズーム",
    processing_title: "作成中",
    processing_steps: [
      "初期化中...",
      "ステップ 2/4: 背景除去中...",
      "ステップ 3/4: スタイル適用中...",
      "ステップ 4/4: 最終確認中...",
    ],
    processing_set: "拡張ステッカーセットを生成中 (3種類のバリエーション)...",
    result_verified: "検証済み：512x512px PNG",
    result_title: "ステッカー完成！",
    result_style_label: "スタイル",
    result_saved: "コレクションに保存しました",
    btn_magic_wand: "背景を修正",
    btn_reset: "新規作成",
    btn_reuse: "同じ写真で作成",
    btn_generate_set: "セットを作成",
    btn_download: "PNGをダウンロード",
    btn_retry: "もう一度試す",
    set_title: "ステッカーセット完成！",
    set_desc: "元の画像を元に、スタイルは同じで表情や動きが異なるシリーズを作成しました。",
    error_header: "エラーが発生しました",
    error_upload: "ファイルの読み込みエラー",
    error_process: "作成に失敗しました。もう一度試すか、別の写真を使用してください。",
    error_safety: "安全フィルターによりブロックされました。別の画像を試してください。",
    error_timeout: "サーバーの応答時間が長すぎます。負荷が高い可能性があります。",
    error_no_image: "AIが有効な画像を生成できませんでした。",
    error_cancelled: "生成をキャンセルしました。",
    validation_file_type: "PNG、JPEG、WebP 形式の画像のみ対応しています。",
    validation_file_size: "画像が 10 MB を超えています。別の画像でお試しください。",
    validation_file_corrupt: "画像を読み込めませんでした。ファイルが破損している可能性があります。",
    cancel: "キャンセル",
    footer: "© 2024 Sticker Maker Pro. Powered by Google Gemini.",
    gallery_title: "サンプルギャラリー",
    gallery_subtitle: "他のユーザーが作成した作品を見たり、サンプルをインポートして試してみましょう！",
    gallery_btn_try: "スタイルを使用",
    gallery_btn_import: "サンプルをインポート",
    history_title: "マイコレクション",
    history_subtitle: "このデバイスで作成したすべてのステッカー",
    history_empty: "まだステッカーがありません。最初の1枚を作成しましょう！",
    variation_title: "前のステッカーからバリエーションを作成",
    variation_subtitle: "同じキャラクターとスタイルを維持し、強度を選んで新しい表情やポーズを生成！",
    variation_strength_label: "バリエーション強度",
    variation_strength_low: "微小 (Subtle)",
    variation_strength_low_desc: "微小な表情の変化（笑顔、ウィンク等）、構図は維持",
    variation_strength_medium: "標準 (Moderate)",
    variation_strength_medium_desc: "はっきりとした表情やジェスチャー（いいね、大笑い、手を振る）",
    variation_strength_high: "クリエイティブ (High)",
    variation_strength_high_desc: "ダイナミックなアクション、豊かなリアクション、小物追加",
    variation_prompt_label: "アクション / テーマ（任意）",
    variation_prompt_placeholder: "例：大笑い、サングラス、いいね、ハート手ポーズ...",
    btn_generate_variation: "⚡ バリエーションを生成",
    btn_create_variation_short: "バリエーション作成",
    variation_compare_title: "元ステッカーと新バリエーションの比較",
    compare_original: "元のステッカー",
    compare_variation: "新しいバリエーション",
    tag_variation: "バリエーション",
    processing_variation: "前のステッカーの被写体とスタイルを解析し、バリエーションを生成中...",
    styles: {
      1: { name: "ベクターセルロイド風", features: "太い輪郭、滑らかなグラデーション" },
      2: { name: "手描きマーカー風", features: "インクの線、マーカーの質感" },
      4: { name: "リソグラフ印刷風", features: "網點、版ズレ効果" },
      5: { name: "アメリカンカートゥーン", features: "太い線、2.5D的な立体感" },
      8: { name: "グラフィックノベル風", features: "コミック調、強いコントラスト" },
      10: { name: "レトロラバーホース", features: "1930年代アニメ、モノクロ" },
      11: { name: "フィルム・ノワール風", features: "白黒、ドラマチックな照明" },
      13: { name: "リアル青年コミック風", features: "リアルな人体デッサン、細密ハッチング、映画風の明暗光影" },
      14: { name: "韓国Webtoon精緻風", features: "繊細な墨線、美形リアル、微醺ライティング、淡麗な肌色" },
      15: { name: "ポップベクターWebtoon", features: "55%韓漫美形 + 30%ベクター + 10%青年ハッチング + 5%微立体" },
      16: { name: "レトロ墨絵ノワール誌", features: "50%青年劇画 + 30%レトロ墨感 + 15%美形 + 5%ソフト立体" },
      17: { name: "ネオセルWebtoon立体", features: "45%セル画調 + 35%韓漫光彩 + 15%躍動ライン + 5%フィギュア質感" },
    }
  }
};

export const GALLERY_ITEMS: GalleryItem[] = [
  { id: '1', imageUrl: 'images/illus01.png', styleId: 1, author: 'Vector_Pro' },
  { id: '2', imageUrl: 'images/illus01.png', styleId: 2, author: 'Marker_Art' },
  { id: '4', imageUrl: 'images/illus04.png', styleId: 4, author: 'Riso_Fan' },
  { id: '5', imageUrl: 'images/illus05.png', styleId: 5, author: 'Toon_King' },
  { id: '8', imageUrl: 'images/illus06.png', styleId: 8, author: 'Comic_Noir' },
  { id: '10', imageUrl: 'images/illus010.png.png', styleId: 10, author: 'Retro_Toon' },
  { id: '11', imageUrl: 'images/illus06.png', styleId: 11, author: 'Noir_Fan' },
  { id: '13', imageUrl: 'images/illus011.png', styleId: 13, author: 'Seinen_Noir' },
  { id: '14', imageUrl: 'images/illus012.png', styleId: 14, author: 'Manhwa_Webtoon' },
  { id: '15', imageUrl: 'images/illus00.png', styleId: 15, author: 'Pop_Manhwa' },
  { id: '16', imageUrl: 'images/illus06.png', styleId: 16, author: 'Vintage_Noir' },
  { id: '17', imageUrl: 'images/illus02.png', styleId: 17, author: 'NeoCel_Artist' },
];
